### ISSUE TITLE
Can't turn off brute force matcher

### ISSUE THREAD

**Issue by mjtic12** [GoSimpleLLC/nbvcxz#31]
Hey there,

first: nice lib, thanks for your work!

My Problem: 
I would like to use your library with only my own password matchers.
The problem are the BruteForceMatches or the isRandom-check. Is there a way to turn it off?

**Comment by Tostino** [comment]
Glad you like the library!
I think I need to understand the use case a little better before I can point you in a direction to go, or make any changes.

Is it that you'd like to provide an alternate implementation of the BruteForceMatch that has a different scoring method?

The main thing is, the algorithm really only works if you have a match that covers every part of the password.  That is why the brute force portion wasn't implemented as a PasswordMatcher, and instead hard-coded to ensure there was one for every position in the password, which could then go through the find best combination piece.  

Pretty much, if we ensure there is a single length match for every position in the password, then re-architecting how the BruteForceMatch is handled could be done.

**Comment by mjtic12** [comment]
Hey,

thanks for the fast reply.
Yes, that was also my result while forking and testing my ideas.
I thought i just could turn off the bruteforce part. But then the algorithm failed.

My initial idea was, to achieve a check if every rule from my password guideline is satisfied (by looking into the matches, if my matches appears there) + a strength password with the result of the entropies.

Or with the sum of the entropy for it... like

LengthMatcher - hardcoded Entropy (HE) 1
SpecialCharMatcher - HE 1
UpperCase/LowerCaseMatcher - HE 1/ HE 1
...

so i just need to check if the sums like sum= 4.
But that can't work, because of the good algorithm.
My understanding how it work is now better and i just do my simple rule check on my own and use your untouched lib to check for the strength.

Thank you very much again!

**Comment by Tostino** [comment]
Ah, yeah it would be WAY simpler as i'm sure you've seen to just write a new piece of code to do those simple checks rather than trying to hack it into Nbvcxz.  The main intention for allowing custom matchers / matches is so if someone has some special need that wasn't covered by the library, it could be easily extended to do what they need.  For example, maybe they wanted a matcher that would work on some regex they came up with, and they could accurately calculate an entropy for it.  As long as it works within how the system / algorithm was designed, it'll work fine.

Glad you found a solution.
