### ISSUE TITLE
Add score enum indicating password strength

### ISSUE THREAD

**Issue by Rapster** [GoSimpleLLC/nbvcxz#39]
First, thank you for providing that awesome library!

Second, I need just like `zxcvbn` does, an enum indicating if the password is either, worst, bad, wak, good or strong. According to `zxcvbn`, it's possible to do that, based on guesses:

```
result.score      # Integer from 0-4 (useful for implementing a strength bar)

  0 # too guessable: risky password. (guesses < 10^3)

  1 # very guessable: protection from throttled online attacks. (guesses < 10^6)

  2 # somewhat guessable: protection from unthrottled online attacks. (guesses < 10^8)

  3 # safely unguessable: moderate protection from offline slow-hash scenario. (guesses < 10^10)

  4 # very unguessable: strong protection from offline slow-hash scenario. (guesses >= 10^10)
```

This would be accessible calling `getScore()` in `me.gosimple.nbvcxz.scoring#Result`

**Comment by Tostino** [comment]
When I was implementing I had thought about that, but decided not to put that into Nbvcxz because those scores mean different things to different people, and basing it on # of guesses doesn't really do it justice.

For instance if you've hashed your passwords with md5, the number of guesses / sec possible if that password is tried offline is so different than if you had hashed your passwords with bcrypt(14) for example.

So to get a score, you really need to base it on the "time to crack" we calculate, not the estimated guesses required for the password.

At that point, if there is a good consensus on what a good "time to crack" threshold would be for each of those scores, it would be easy to implement...

I'd love to hear more thoughts on this.

**Comment by Rapster** [comment]
I understand, but since our front-end password feeback is based on zxcvbn, we have to be coherent on server-side. So I guess a default impl should be based on time-to-crack, but nbvcxz should give the possibility to override that default impl.

**Comment by Tostino** [comment]
Hmm, maybe instead of absolute values, we can have the score be related to the minimum entropy set within the configuration?

That way we can always return a relevant score based on what the minimum entropy is set to, rather than arbitrary values. Just a thought.

I already did some work this past weekend to make it so minimum entropy can be set by passing in a time to crack rather and a cracking algorithm rather than having to do that math yourself and figure out what a good value is... commit:  1154923

**Comment by Togrias** [comment]
Hi,

I too have a front-end based on zxcvbn. It would be nice if both ends would give the same results. So if the front-end tells the user their password is acceptable, then the backend should accept it also.

**Comment by Tostino** [comment]
Agreed that being compatible is a good goal for those reasons, though keep in mind that Nbvcxz is not trying to be a direct clone of Zxcvbn, but also expands on the algorithms provided and fixes some structural issues. They are not guaranteed to score a password the same just FYI.

I will try and get the work done on this sooner rather than later, my day job has been killing me lately.

**Comment by Tostino** [comment]
Alright I implemented the most basic scoring algorithm right from zxcvbn in commit: https://github.com/GoSimpleLLC/nbvcxz/commit/7e3b35053746f184928fb87aeefd36226e3dc908

I plan on implementing a more advanced way of scoring based on time rather than guesses in the future, but this is a first step.  Any comments before I push out a new release?
@Rapster @Togrias

**Comment by Tostino** [comment]
Going to close this as release 1.4.3 is now out.

@Togrias Yes, sadly if you want something that will estimate exactly the same in Java as JS, using something else is the only real option.  I had originally intended to do an exact port, but I noticed too many flaws with that approach after testing.
