### ISSUE TITLE
Multiple simultaneous connections cause heap dump

### ISSUE THREAD

**Issue by gregholliday** [GoSimpleLLC/nbvcxz#54]
Not sure if this is an issue or if we haven't implemented something correctly.  We're trying to use the library for password validation, and we've found that 200+ simultaneous connections fill the JVM heap and crash our servers.  Basically we have an API enpoint that the user calls and passes their password.  When then call nbvcxz.estimate(password).

**Comment by Tostino** [comment]
Hmm, are you using the same Nbvcxz object for all endpoint calls, or are you creating a new object per-call? Just wondering if you could provide something so I can try and reproduce so I can look to see what is actually going on.

**Comment by Tostino** [comment]
@gregholliday Just wanted to check back on this and see if you figured it out or are able to provide an example of what is happening if not?

**Comment by gregholliday** [comment]
Sorry, it's been very crazy the past couple of weeks.  I've tried several different things, but here is a code snippet that I know will reproduce the issue:

public int getPasswordScore(String password){
  Nbvcxz nbvcx = new Nbvcxz();
  Result result = nbvcxz.estimate(password);  //using this line for debugging
  return result.getBasicScore();
}

Also, this is being deployed to a Payara/Glassfish 4 server.

**Comment by Tostino** [comment]
If possible, you really should avoid creating a new Nbvcxz instance for every estimation. It has to load up all the dictionaries, etc into hash tables.

That is all fine and good, until you have a whole bunch of people hitting your service at once.

I can see if there are any easy wins for reducing the memory footprint of each Nbvcxz object, but in the end it's better to reuse the object.

**Comment by Tostino** [comment]
@gregholliday I just benchmarked creating 150 Nbvcxz objects in a loop to look at the allocations:
![image](https://user-images.githubusercontent.com/8227578/82385398-08690800-9a00-11ea-8d96-c98c6c9e964e.png)

So I looked where that time was being spent, and it became obvious I did something stupid.
In the ConfigurationBuilder class, we have all the default values, and all the defaults were created from scratch every time rather than creating them once and returning the same objects.

I made some changes in commit: f7ed1d7153c8eead0b402e27865ca0bb4e9239ed

Here are the results for allocations after:
![image](https://user-images.githubusercontent.com/8227578/82385888-2125ed80-9a01-11ea-81ff-df489f4ff2d4.png)

**Comment by gregholliday** [comment]
@Tostino Thanks.  I will pull the changes and give it a try.

**Comment by Tostino** [comment]
@gregholliday Just wondering if this actually fixed the issue you were seeing?

**Comment by Tostino** [comment]
Going to call this closed with release 1.5.0
