### ISSUE TITLE
"very common password" feedback for a strong password

### ISSUE THREAD

**Issue by 40rn05lyv** [GoSimpleLLC/nbvcxz#64]
Hi, I tried to estimate password "discovercowboycow"

    Nbvcxz nbvcxz = new Nbvcxz();
    final Result result = nbvcxz.estimate("discovercowboycow");

The result has basic score of 3 (our of 4) which is considered a strong password, however a feedback `(result.getFeedback().getWarning())` returns message _"This is a very common password."_ which is just inappropriate here.

I think passwords with score 3 and 4 don't need to have a warning message (just like in original zxcvbn)

**Comment by Tostino** [comment]
So this has two parts, first is that I agree that the feedback could be better here, it takes the largest entropy part of the password to figure out what feedback to give.

Secondly, the "basicScore" was implemented to work with the same way as original zxcvbn, but that's it. It doesn't integrate with the minimum entropy for example, giving a different 0-4 score depending on what the minimumEntropy or crackingHardwareCost.

This could be changed, but as of right now, the "basicScore" isn't all that useful IMO. I implemented it by request, it was originally left out of my design because I didn't like how it was designed in zxcvbn. 
You can see the code for it here: 
```
/**
* This scoring function returns an int from 0-4 to indicate the score of this password
* using the same semantics as zxcvbn.
*
* @return Score
* <br>0: risky password: "too guessable"
* <br>1: modest protection from throttled online attacks: "very guessable"
* <br>2: modest protection from unthrottled online attacks: "somewhat guessable"
* <br>3: modest protection from offline attacks: "safely unguessable" (assuming a salted, slow hash function)
* <br>4: strong protection from offline attacks: "very unguessable" (assuming a salted, slow hash function)
*/
public int getBasicScore()
{
    final BigDecimal guesses = getGuesses();
    if (guesses.compareTo(BigDecimal.valueOf( 1e3)) == -1)
        return 0;
    else if (guesses.compareTo(BigDecimal.valueOf( 1e6)) == -1)
        return 1;
    else if (guesses.compareTo(BigDecimal.valueOf(1e8)) == -1)
        return 2;
    else if (guesses.compareTo(BigDecimal.valueOf(1e10)) == -1)
        return 3;
    else
        return 4;
}
```

Right now I think it's too dumb to use effectively, which is why you get a basicScore of 4, even though at this point that isn't actually a secure enough password in 2021 since the "guesses" are simply static values that were taken directly from zxcvbn. It should take into account the rest of the enhancements that Nbvcxz has for setting minimumEntropy, and crackingHardwareCost.

You get warning feedback if you have not met the minimum entropy requirements, and this password doesn't meet the default minimum entropy due to matching quite a few very common words that appear high up in different dictionaries.

**Comment by Tostino** [comment]
And here is the previous discussion when I implemented the basic score: https://github.com/GoSimpleLLC/nbvcxz/issues/39
